image: node:10

cache:
  key: "kanva-cache"
  paths:
  - node_modules

stages:
- build
- deploy

build:
  stage: build
  artifacts:
    paths:
    - dist/
  script:
  - yarn
  - yarn build
  - yarn lint
  - yarn test
  - yarn dist
