image: node:10

cache:
  key: "kanva-cache"
  paths:
  - node_modules

stages:
- build
- deploy

build:
  stage: build
  artifacts:
    paths:
    - dist/
  script:
  - yarn
  - yarn lint
  - yarn test
  - yarn build
  - yarn dist

deploy:
  stage: deploy
  image: python:latest
  cache: {}
  script:
  - chmod 755 ./scripts/deploy.sh && ./scripts/deploy.sh
  only:
  - master
