language: python

services:
- docker

cache:
  yarn: true

stages:
- test
- build
- name: deploy
  if: branch = master AND type = push

before_install:
- nvm install 11
- npm i -g yarn

install:
- yarn install

jobs:
  include:
  - stage: test
    script:
    - yarn lint
    - yarn test
  - stage: build
    script:
    - yarn build
  - stage: deploy
    before_script:
    - chmod -R 755 ./scripts
    - pip install awscli
    - sudo apt-get update && sudo apt-get install jq -y
    - . ./scripts/kubernetes-setup.sh
    script:
    - yarn build:all
    - yarn deploy

branches:
  only:
  - master
